import { ArrowRight, Calendar, Check, Clock3, Flame, MapPin, Phone, Sparkles, Star, Tag, Utensils } from "lucide-react";
import Header from "@/components/Header";
import MenuGrid from "@/components/MenuGrid";
import Gallery from "@/components/Gallery";
import { categories, site } from "@/data/site";

export default function Home() {
  const whatsapp = `https://wa.me/${site.whatsapp}`;
  return <>
    <Header />
    <main>
      <section id="hero" className="relative flex min-h-screen items-center overflow-hidden pb-16 pt-24">
        <div className="absolute inset-0 z-0"><img src="https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=2000&q=85" alt="Pizza artesanal" className="h-full w-full scale-105 object-cover" /><div className="absolute inset-0 bg-gradient-to-r from-darkBg via-darkBg/80 to-darkBg/40" /><div className="absolute inset-0 bg-gradient-to-t from-darkBg via-transparent to-black/60" /></div>
        <div className="relative z-10 mx-auto grid w-full max-w-7xl grid-cols-1 items-center gap-12 px-4 sm:px-6 lg:grid-cols-12 lg:px-8">
          <div className="lg:col-span-8"><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/10 px-4 py-1.5 text-xs font-extrabold uppercase tracking-widest text-brandYellow backdrop-blur-md"><Flame className="h-4 w-4 text-brandRed" /><span>{site.badge}</span></div><h2 className="mb-2 text-xs font-black uppercase tracking-[0.4em] text-brandYellow sm:text-sm">{site.eyebrow}</h2><h1 className="mb-6 whitespace-pre-line text-4xl font-black uppercase leading-[0.95] tracking-tight text-white sm:text-6xl md:text-7xl">{site.heroTitle}</h1><p className="mb-8 max-w-2xl text-lg font-medium leading-relaxed text-textGray sm:text-xl">{site.heroText}</p><div className="flex flex-col gap-4 sm:flex-row"><a href={whatsapp} target="_blank" rel="noreferrer" className="inline-flex items-center justify-center gap-3 rounded-full bg-brandYellow px-8 py-4 text-sm font-black uppercase tracking-wider text-black shadow-xl hover:scale-105"><span>FALAR NO WHATSAPP</span><ArrowRight className="h-5 w-5" /></a><a href="#cardapio" className="inline-flex items-center justify-center gap-3 rounded-full border border-white/20 bg-white/10 px-8 py-4 text-sm font-black uppercase tracking-wider text-white backdrop-blur-md hover:border-brandYellow">VER CARDÁPIO</a></div></div>
          <div className="hidden flex-col items-end justify-end gap-4 lg:col-span-4 lg:flex"><Info icon={<Sparkles />} value={site.stats[0][0]} label={site.stats[0][1]} /><Info icon={<Flame />} value="Artesanal" label="Preparado na hora" /><Info icon={<Utensils />} value="Para todos" label="Família, amigos e encontros" /></div>
        </div>
      </section>

      <section id="categorias" className="border-t border-white/5 bg-darkBg py-20"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="mb-12"><span className="mb-2 block text-xs font-extrabold uppercase tracking-widest text-brandYellow">VARIEDADE</span><h2 className="text-3xl font-black uppercase tracking-tight text-white sm:text-5xl">TUDO O QUE VOCÊ <span className="text-brandYellow">QUER COMER.</span></h2></div><div className="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-5">{categories.map(item=><div key={item.title} className="group relative h-80 overflow-hidden rounded-2xl border border-white/10 bg-darkCard hover:border-brandYellow/50"><img src={item.image} alt={item.title} className="h-full w-full object-cover transition-transform duration-500 group-hover:scale-110" /><div className="absolute inset-0 bg-gradient-to-t from-darkBg via-darkBg/60 to-transparent" /><div className="absolute inset-x-0 bottom-0 p-6"><h3 className="text-xl font-black text-white group-hover:text-brandYellow">{item.title}</h3><p className="mt-2 text-xs text-textGray">{item.description}</p></div></div>)}</div></div></section>

      {site.rodizio.enabled && <section id="rodizio" className="relative overflow-hidden bg-brandYellow py-20 text-black"><div className="relative z-10 mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="grid grid-cols-1 items-center gap-12 lg:grid-cols-12"><div className="lg:col-span-7"><span className="mb-6 inline-block rounded-full bg-black px-4 py-1.5 text-xs font-extrabold uppercase tracking-widest text-brandYellow">EXPERIÊNCIA DA CASA</span><h2 className="mb-4 text-4xl font-black uppercase leading-none tracking-tight sm:text-6xl">{site.rodizio.title}</h2><p className="mb-8 max-w-xl text-lg font-semibold text-black/80 sm:text-xl">{site.rodizio.subtitle}</p><div className="mb-8 flex items-baseline gap-4"><span className="text-5xl font-black tracking-tight sm:text-7xl">{site.rodizio.price}</span><span className="text-lg font-extrabold uppercase text-black/70">/ pessoa</span></div><ul className="mb-8 grid grid-cols-1 gap-3 sm:grid-cols-2">{site.rodizio.items.map(text=><li key={text} className="flex items-center gap-2 text-sm font-extrabold"><span className="flex h-5 w-5 items-center justify-center rounded-full bg-black text-brandYellow"><Check className="h-3.5 w-3.5" /></span>{text}</li>)}</ul><a href={whatsapp} target="_blank" rel="noreferrer" className="inline-flex items-center gap-3 rounded-full bg-black px-8 py-4 text-sm font-black uppercase tracking-wider text-white hover:scale-105"><Calendar className="h-5 w-5 text-brandYellow" /> Quero reservar</a></div><div className="relative lg:col-span-5"><div className="overflow-hidden rounded-3xl border-4 border-black/10 shadow-2xl"><img src="https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1000&q=80" alt="Experiência gastronômica" className="h-[450px] w-full object-cover" /></div></div></div></div></section>}

      <section id="cardapio" className="border-t border-white/5 bg-darkBg py-20"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="mb-12"><span className="mb-2 block text-xs font-extrabold uppercase tracking-widest text-brandYellow">CARDÁPIO</span><h2 className="text-3xl font-black uppercase tracking-tight text-white sm:text-5xl">OS FAVORITOS <span className="text-brandYellow">DA CASA.</span></h2></div><MenuGrid /></div></section>

      <section className="relative overflow-hidden py-20"><div className="absolute inset-0"><img src="https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=2000&q=80" alt="Oferta" className="h-full w-full object-cover" /><div className="absolute inset-0 bg-darkBg/90" /></div><div className="relative z-10 mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="rounded-3xl border border-brandRed/40 bg-gradient-to-r from-brandRed-dark via-brandRed to-brandRed-dark p-8 shadow-2xl sm:p-14"><div className="max-w-2xl"><div className="mb-4 inline-flex items-center gap-2 rounded-full bg-black/40 px-4 py-1.5 text-xs font-black uppercase tracking-widest text-brandYellow"><Tag className="h-4 w-4" /> OFERTA DA SEMANA</div><h2 className="mb-4 text-4xl font-black uppercase leading-none text-white sm:text-6xl">{site.offer.title}</h2><div className="my-4 text-2xl font-black uppercase text-brandYellow sm:text-4xl">{site.offer.highlight}</div><p className="mb-8 text-sm text-white/90 sm:text-base">{site.offer.text}</p><div className="flex flex-col items-start gap-6 sm:flex-row sm:items-center"><div><span className="block text-xs font-bold uppercase text-white/70">Por apenas</span><span className="text-4xl font-black text-white sm:text-5xl">{site.offer.price}</span></div><a href={whatsapp} target="_blank" rel="noreferrer" className="rounded-full bg-brandYellow px-8 py-4 text-xs font-black uppercase tracking-wider text-black hover:scale-105">Aproveitar oferta</a></div></div></div></div></section>

      <section id="sobre" className="border-t border-white/5 bg-darkBg py-20"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="grid grid-cols-1 items-center gap-12 lg:grid-cols-12"><div className="lg:col-span-6"><span className="mb-2 block text-xs font-extrabold uppercase tracking-widest text-brandYellow">SOBRE A CASA</span><h2 className="mb-6 text-3xl font-black uppercase leading-none tracking-tight text-white sm:text-5xl">UMA CASA FEITA PARA <span className="text-brandYellow">COMPARTILHAR.</span></h2><p className="mb-8 text-base leading-relaxed text-textGray">Um espaço para reunir a família, comemorar, encontrar os amigos e comer bem. Esta área é o lugar ideal para contar a história, diferenciais e proposta da pizzaria.</p><div className="grid grid-cols-3 gap-6 border-t border-white/10 pt-6">{site.stats.map(([value,label])=><div key={value}><span className="block text-3xl font-black text-brandYellow sm:text-4xl">{value}</span><span className="text-xs font-bold uppercase text-textGray">{label}</span></div>)}</div></div><div className="grid grid-cols-2 gap-4 lg:col-span-6"><img src="https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80" alt="Ambiente" className="h-64 w-full rounded-2xl border border-white/10 object-cover shadow-xl" /><img src="https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=800&q=80" alt="Pizza" className="h-80 w-full rounded-2xl border border-white/10 object-cover shadow-xl" /></div></div></div></section>

      <Gallery />

      <section className="border-t border-white/5 bg-darkCard py-20"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="mx-auto mb-16 max-w-2xl text-center"><span className="mb-2 block text-xs font-extrabold uppercase tracking-widest text-brandYellow">DEPOIMENTOS</span><h2 className="text-3xl font-black uppercase tracking-tight text-white sm:text-5xl">QUEM VEM, <span className="text-brandYellow">QUER VOLTAR.</span></h2><p className="mt-4 text-sm text-textGray">Troque estes exemplos por avaliações reais da pizzaria antes da publicação.</p></div><div className="grid grid-cols-1 gap-8 md:grid-cols-3">{["Pizza muito saborosa e atendimento excelente!", "Ambiente agradável e ótimo para reunir a família.", "Cardápio variado e tudo chegou muito bem preparado."].map((quote,i)=><div key={quote} className="rounded-2xl border border-white/10 bg-darkBg p-8"><div className="mb-4 flex gap-1 text-brandYellow">{Array.from({length:5}).map((_,j)=><Star key={j} className="h-5 w-5 fill-brandYellow" />)}</div><p className="mb-6 text-sm italic text-gray-300">“{quote}”</p><div className="border-t border-white/5 pt-4"><span className="text-sm font-extrabold text-white">Cliente {i+1}</span><span className="block text-xs text-textGray">Avaliação de demonstração</span></div></div>)}</div></div></section>

      <section id="localizacao" className="border-t border-white/5 bg-darkBg py-20"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="grid grid-cols-1 items-center gap-12 lg:grid-cols-12"><div className="lg:col-span-6"><span className="mb-2 block text-xs font-extrabold uppercase tracking-widest text-brandYellow">ONDE ESTAMOS</span><h2 className="mb-6 text-3xl font-black uppercase tracking-tight text-white sm:text-5xl">VENHA NOS <span className="text-brandYellow">VISITAR.</span></h2><div className="mb-8 space-y-6"><Contact icon={<MapPin />} title="Endereço" text={site.address} /><Contact icon={<Clock3 />} title="Horário de funcionamento" text={site.hours} /><Contact icon={<Phone />} title="Reservas & contato" text={site.phone} /></div><a href={whatsapp} target="_blank" rel="noreferrer" className="inline-flex rounded-full bg-brandYellow px-7 py-4 text-sm font-black uppercase text-black hover:scale-105">Falar com a pizzaria</a></div><div className="relative h-[400px] overflow-hidden rounded-3xl border border-white/10 lg:col-span-6">{site.mapEmbed ? <iframe title={`Localização da ${site.name}`} src={site.mapEmbed} width="100%" height="100%" style={{border:0,filter:"grayscale(1) invert(.9) contrast(1.2)"}} loading="lazy" /> : <div className="flex h-full flex-col items-center justify-center bg-darkCard px-8 text-center"><MapPin className="mb-4 h-12 w-12 text-brandYellow" /><p className="text-lg font-black text-white">Mapa da localização</p><p className="mt-2 text-sm text-textGray">Cole aqui o embed do Google Maps da pizzaria.</p></div>}</div></div></div></section>
    </main>
    <footer className="border-t border-white/10 bg-black py-12"><div className="mx-auto flex max-w-7xl flex-col items-center justify-between gap-6 px-4 sm:px-6 md:flex-row lg:px-8"><div><span className="block text-xs font-extrabold uppercase tracking-[0.3em] text-brandYellow">PIZZARIA</span><span className="block text-xl font-black tracking-tight text-white">{site.shortName}</span><p className="mt-2 text-xs text-textGray">{site.address}</p></div><p className="text-center text-xs text-textGray md:text-right">© {new Date().getFullYear()} {site.name}. Todos os direitos reservados.</p></div></footer>
  </>;
}
function Info({icon,value,label}:{icon:React.ReactNode,value:string,label:string}){return <div className="flex max-w-xs items-center gap-4 rounded-2xl border border-white/10 bg-darkCard/90 p-4 shadow-2xl backdrop-blur-lg"><div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-xl bg-brandYellow/10 text-brandYellow">{icon}</div><div><p className="text-xl font-black text-white">{value}</p><p className="text-xs text-textGray">{label}</p></div></div>}
function Contact({icon,title,text}:{icon:React.ReactNode,title:string,text:string}){return <div className="flex items-start gap-4"><div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl bg-brandYellow/10 text-brandYellow">{icon}</div><div><h3 className="text-lg font-extrabold text-white">{title}</h3><p className="text-sm text-textGray">{text}</p></div></div>}
